return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "css",
      "dockerfile",
      "go",
      "diff",
      "html",
      "hcl",
      "javascript",
      "json",
      "gitignore",
      "lua",
      "markdown",
      "markdown_inline",
      "scss",
      "tsx",
      "jsonc",
      "typescript",
      "graphql",
      "yaml",
      "toml",
      "fish",
      "ruby",
      "prisma",
      "php",
      "rust",
    },
  },
}
